var itemList = [
    "Moo T-shirt",
    "Halberd Axe",
    "Enchanted Tree",
    "Moo Moo T-shirt",
    "Sassy's Cloak",
    "Book of Knowledge",
    "Ragnarok",
    "Tectonic",
    "Mask of Valor",
    "Holy Aura",
    "Demonic Ultimate",
    "Doom Horn",
    "Jagged Sword",
    "Jagged Blade",
    "Demon Edge",
    "Gem of Shadow",
    "Immunity Necklace",
    "Replication",
    "Balnazzar's Hand",
    "Eternal Aura",
    "Dual Sword",
    "Ultimate",
    "Ani Cages",
    "Cage Large",
    "Cage Medium",
    "Cage Small",
    "Frog",
    "Satanic Chicken",
    "Animals",
    "Runes",
    "Explosive Barrel",
    "Secret Place",
    "Fountain of the Thunderbluff / Rexxar's Shop",
    "Krechek's Soul",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hastarium",
    "Javelin",
    "Savior's Claw",
    "Evil Soul",
    "Warhammer",
    "Imperial Axe",
    "Swordstaff",
    "Coral Blades",
    "Red Boots",
    "Ruthless Gauntlet",
    "Sapphire Ring",
    "Heroism Mask",
    "Leremias",
    "Hood of Cunning",
    "Villainous Shield",
    "Helm of King",
    "Breast Plate",
    "Mithril T-shirt",
    "Celestial Ring",
    "Studded Leather",
    "Elune's Cloak",
    "Sefer Buckler",
    "Helm of Hador",
    "Dagger of Escape",
    "Gauntlets",
    "Slippers",
    "Robe",
    "Good Soul",
    "Belt of Ogre",
    "Quel'Thalas",
    "Robe of the Magi",
    "Neelanjali Ruby",
    "Masakari",
    "Aeglos",
    "Chakram",
    "Angel's Orb",
    "Abyssimal",
    "Searing Edge",
    "Climber's Hammer",
    "Chitinous Blade",
    "Assault",
    "Vicious",
    "Copper Sword",
    "Archmagi Blade",
    "Orb of Fire",
    "Orb of Frost",
    "Orb of Shadow",
    "Orb of Light"
];